### PR TITLE
fixes EETypeLoadException issue: export class DelegateCommand

### PR DESCRIPTION
**Pull request by tian-lt**
### Description of the changes:
- Exports class DelegateCommand
- Removes the implementation of C# DelegateCommand
- Adjusts the using spots

### How changes were validated:

- Build passed
- EETypeLoadException has gone
- CI pipeline and UT is not applicable at current stage.

### CODE REVIEW

**Comment by tian-lt** [comment]
Hi @hanzhang54 @wmx16835, Could you help review this PR? thanks

**Comment by tian-lt** [comment]
Pushed more commits.
Hi @hanzhang54 @wmx16835, could you help review this PR again, thanks!

**Review by mingxwa — APPROVED** [review]
LGTM

**Review by hanzhang54 — APPROVED** [review]
LGTM

**Pull request merged**
