### PR TITLE
Fixup tests (#1429)

### PR DESCRIPTION
**Pull request by hanzhang54**
(cherry picked from commit 66ad328d0018c360c1a0dc766f994c7fdb7d4a3f)

### Description of the changes:
- Removed unneeded "ToString" calls
- Fixed typos
- Renamed "fEButtonState" to "FEButtonState"

### How changes were validated:

- Passed build and most UI tests. Some UI tests are not applicable at current stage.

### CODE REVIEW

**Comment by tian-lt** [comment]
Do we have link to the original PR?

**Comment by hanzhang54** [comment]
> Do we have link to the original PR?
The original link for this PR is missing, so I only recorded the commit id. Please check https://github.com/microsoft/calculator/pull/1429.

**Comment by tian-lt** [comment]
Good to know that. Interestingly, the link of [microsoft#1429](https://github.com/microsoft/calculator/pull/1429) gives 404 back to me. 😅

**Review by tian-lt — APPROVED** [review]
Regarding the [original commit](https://github.com/tian-lt/calculator/commit/66ad328d0018c360c1a0dc766f994c7fdb7d4a3f), this backporting looks good to me.

**Pull request merged**
